server:
  port: 8600
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: downloader-in
      kafka:
        binder:
          brokers: localhost:29092
service:
  zeus:
    hostname: http://localhost:8610
