#we use java
language: java

#we add the java development kit (jdk)
jdk:
  - openjdk8
  
# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "cdrommens"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

after_success:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
